version: '3'

services:

  wordpress:
    image: wordpress
    ports:
      - 8080:80
    # environment:
    #   WORDPRESS_DB_HOST: db
    #   WORDPRESS_DB_USER: exampleuser
    #   WORDPRESS_DB_PASSWORD: examplepass
    #   WORDPRESS_DB_NAME: exampledb
    env_file:
      - .env
    volumes:
      - wordpress_v:/var/www/html
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_ROOT_PASSWORD: examplerootpass
    volumes:
      - db_v:/var/lib/mysql

volumes:
  db_v:
  wordpress_v: